import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Twitter from "@/components/cards/Twitter";

const API_URL = "http://localhost:3000/api";

export default function Home() {
  const [error, setError] = useState("");
  const [url, setUrl] = useState("");
  const [metaInfo, setMetaInfo] = useState({});

  const getMetaInfo = (source) => {
    const parser = new DOMParser();
    const dom = parser.parseFromString(source, "text/html");
    const metaTags = dom.getElementsByTagName("meta");
    const metaObj = {};

    for (let meta of metaTags) {
      const key = meta.getAttribute("name") || meta.getAttribute("property");
      if (key) {
        metaObj[key] = meta.getAttribute("content");
      }
    }

    setMetaInfo(metaObj);
  };

  const fetchSource = async () => {
    const res = await fetch(API_URL + "/meta" + "?url=" + url);
    const { source, err } = await res.json();
    if (err) {
      setError(err);
      setMetaInfo({});
    } else {
      setError("");
      getMetaInfo(source);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Get Meta Info</h1>
        {error && <p>{error}</p>}
        <input
          type="text"
          onChange={(e) => setUrl(e.target.value)}
          placeholder="Enter any url"
        />
        <button onClick={fetchSource}>Get</button>
        {Object.entries(metaInfo).length > 0 && <Twitter {...metaInfo} />}
      </main>
    </>
  );
}
